package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const goldenCasePath = "../../../spec/examples/cases/fragment-happy-path.case.json"

func runGenerateTestCmd(t *testing.T, framework, outPath string) (string, int) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	code := run([]string{
		"generate", "test",
		"--case", goldenCasePath,
		"--framework", framework,
		"--out", outPath,
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("generate test --framework %s exit = %d, stderr=%q", framework, code, stderr.String())
	}
	b, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	return string(b), code
}

func TestGenerateTestJestEmitsFullTestFile(t *testing.T) {
	out := filepath.Join(t.TempDir(), "checkout.test.ts")
	src, _ := runGenerateTestCmd(t, "jest", out)
	for _, want := range []string{
		"describe(",
		"it(",
		"import { Softprobe } from '@softprobe/softprobe-js'",
		"session.findInCase(",
		"session.mockOutbound(",
		"Generated by `softprobe generate test`",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("jest output missing %q; got:\n%s", want, src)
		}
	}
}

func TestGenerateTestVitestUsesVitestImports(t *testing.T) {
	out := filepath.Join(t.TempDir(), "checkout.test.ts")
	src, _ := runGenerateTestCmd(t, "vitest", out)
	if !strings.Contains(src, "from 'vitest'") {
		t.Fatalf("vitest output missing vitest import:\n%s", src)
	}
	if !strings.Contains(src, "describe(") || !strings.Contains(src, "it(") {
		t.Fatalf("vitest output missing describe/it:\n%s", src)
	}
}

func TestGenerateTestPytestEmitsAsyncFunction(t *testing.T) {
	out := filepath.Join(t.TempDir(), "test_checkout.py")
	src, _ := runGenerateTestCmd(t, "pytest", out)
	for _, want := range []string{
		"import pytest",
		"from softprobe import Softprobe",
		"@pytest.mark.asyncio",
		"async def test_",
		"session.find_in_case(",
		"session.mock_outbound(",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("pytest output missing %q; got:\n%s", want, src)
		}
	}
}

func TestGenerateTestJUnitEmitsClass(t *testing.T) {
	out := filepath.Join(t.TempDir(), "CheckoutTest.java")
	src, _ := runGenerateTestCmd(t, "junit", out)
	for _, want := range []string{
		"import org.junit.jupiter.api.Test",
		"import io.softprobe.Softprobe",
		"class CheckoutTest",
		"@Test",
		"session.findInCase()",
		"session.mockOutbound()",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("junit output missing %q; got:\n%s", want, src)
		}
	}
}

func TestGenerateTestUnknownFrameworkFailsWithInvalidArgs(t *testing.T) {
	out := filepath.Join(t.TempDir(), "x.test.ts")
	var stdout, stderr bytes.Buffer
	code := run([]string{
		"generate", "test",
		"--case", goldenCasePath,
		"--framework", "cypress",
		"--out", out,
	}, &stdout, &stderr)
	if code != exitInvalidArgs {
		t.Fatalf("exit = %d, want %d for unknown framework", code, exitInvalidArgs)
	}
}

func TestGenerateTestJSONEnvelopeReportsOutput(t *testing.T) {
	out := filepath.Join(t.TempDir(), "checkout.test.ts")
	var stdout, stderr bytes.Buffer
	code := run([]string{
		"generate", "test",
		"--case", goldenCasePath,
		"--framework", "jest",
		"--out", out,
		"--json",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("exit = %d, stderr=%q", code, stderr.String())
	}
	var resp struct {
		Status       string `json:"status"`
		ExitCode     int    `json:"exitCode"`
		OutputPath   string `json:"outputPath"`
		Framework    string `json:"framework"`
		RulesEmitted int    `json:"rulesEmitted"`
		CaseID       string `json:"caseId"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &resp); err != nil {
		t.Fatalf("unmarshal: %v; raw=%s", err, stdout.String())
	}
	if resp.Status != "ok" || resp.Framework != "jest" {
		t.Fatalf("resp = %+v", resp)
	}
	if resp.OutputPath != out {
		t.Fatalf("outputPath = %q, want %q", resp.OutputPath, out)
	}
	if resp.CaseID == "" {
		t.Fatal("caseId empty")
	}
}
