package main

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// jestSessionRule describes one outbound hop emitted by `generate jest-session`
// as a `findInCase` + `mockOutbound` pair. There is no `replay` action; the
// SDK materializes the captured response into a plain `mock` rule at test
// setup time (see `docs/design.md` §3.2 / §3.2.3).
type jestSessionRule struct {
	Method    string
	Path      string
	Direction string
}

func generateJestSessionModule(casePath, outPath string, doc caseDocument) (string, error) {
	rules := extractJestSessionRules(doc)
	absCasePath, err := filepath.Abs(casePath)
	if err != nil {
		return "", err
	}
	absOutPath, err := filepath.Abs(outPath)
	if err != nil {
		return "", err
	}
	relCasePath, err := filepath.Rel(filepath.Dir(absOutPath), absCasePath)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	buf.WriteString("// Generated by `softprobe generate jest-session` - do not edit by hand.\n\n")
	buf.WriteString("import path from 'path';\n")
	buf.WriteString("import { Softprobe } from '@softprobe/softprobe-js';\n\n")
	buf.WriteString("const generatedDir = path.dirname(__filename);\n\n")
	buf.WriteString("export async function startReplaySession(): Promise<{ sessionId: string; close: () => Promise<void> }> {\n")
	buf.WriteString("  const softprobe = new Softprobe();\n")
	buf.WriteString("  const session = await softprobe.startSession({ mode: 'replay' });\n")
	buf.WriteString(fmt.Sprintf("  await session.loadCaseFromFile(path.join(generatedDir, %q));\n\n", filepath.ToSlash(relCasePath)))
	for i, rule := range rules {
		buf.WriteString(fmt.Sprintf("  const hit%d = session.findInCase({\n", i))
		if rule.Direction != "" {
			buf.WriteString(fmt.Sprintf("    direction: %q,\n", rule.Direction))
		}
		if rule.Method != "" {
			buf.WriteString(fmt.Sprintf("    method: %q,\n", rule.Method))
		}
		if rule.Path != "" {
			buf.WriteString(fmt.Sprintf("    path: %q,\n", rule.Path))
		}
		buf.WriteString("  });\n")
		buf.WriteString("  await session.mockOutbound({\n")
		if rule.Direction != "" {
			buf.WriteString(fmt.Sprintf("    direction: %q,\n", rule.Direction))
		}
		if rule.Method != "" {
			buf.WriteString(fmt.Sprintf("    method: %q,\n", rule.Method))
		}
		if rule.Path != "" {
			buf.WriteString(fmt.Sprintf("    path: %q,\n", rule.Path))
		}
		buf.WriteString(fmt.Sprintf("    response: hit%d.response,\n", i))
		buf.WriteString("  });\n\n")
	}
	buf.WriteString("  return {\n")
	buf.WriteString("    sessionId: session.id,\n")
	buf.WriteString("    close: () => session.close(),\n")
	buf.WriteString("  };\n")
	buf.WriteString("}\n")

	return buf.String(), nil
}

func extractJestSessionRules(doc caseDocument) []jestSessionRule {
	rules := make([]jestSessionRule, 0, 4)
	seen := make(map[string]struct{})

	for _, trace := range doc.Traces {
		for _, resource := range trace.ResourceSpans {
			for _, scope := range resource.ScopeSpans {
				for _, sp := range scope.Spans {
					if spanAttrString(sp, "sp.span.type") != "extract" {
						continue
					}
					method := firstCaseAttr(sp, "http.request.method", "http.request.header.:method")
					path := firstCaseAttr(sp, "url.path")
					direction := firstCaseAttr(sp, "sp.traffic.direction")
					if path == "" || direction == "" {
						continue
					}
					key := strings.Join([]string{direction, method, path}, "\x00")
					if _, ok := seen[key]; ok {
						continue
					}
					seen[key] = struct{}{}
					rules = append(rules, jestSessionRule{
						Method:    method,
						Path:      path,
						Direction: direction,
					})
				}
			}
		}
	}

	sort.SliceStable(rules, func(i, j int) bool {
		if rules[i].Path != rules[j].Path {
			return rules[i].Path < rules[j].Path
		}
		if rules[i].Method != rules[j].Method {
			return rules[i].Method < rules[j].Method
		}
		return rules[i].Direction < rules[j].Direction
	})

	return rules
}

func firstCaseAttr(sp span, keys ...string) string {
	for _, key := range keys {
		if got := spanAttrString(sp, key); got != "" {
			return got
		}
	}
	return ""
}

func spanAttrString(sp span, key string) string {
	for _, attr := range sp.Attributes {
		if attr.Key != key {
			continue
		}
		if attr.Value.StringValue != "" {
			return attr.Value.StringValue
		}
	}
	return ""
}
