// Generated by `softprobe generate jest-session` - do not edit by hand.

import path from 'path';
import { Softprobe } from '@softprobe/softprobe-js';

const generatedDir = path.dirname(__filename);

export async function startReplaySession(): Promise<{ sessionId: string; close: () => Promise<void> }> {
  const softprobe = new Softprobe();
  const session = await softprobe.startSession({ mode: 'replay' });
  await session.loadCaseFromFile(path.join(generatedDir, '../../../../e2e/captured.case.json'));

  const hit0 = session.findInCase({
    direction: 'outbound',
    method: 'GET',
    path: '/fragment',
  });
  await session.mockOutbound({
    direction: 'outbound',
    method: 'GET',
    path: '/fragment',
    response: hit0.response,
  });

  const hit1 = session.findInCase({
    direction: 'outbound',
    method: 'GET',
    path: '/hello',
  });
  await session.mockOutbound({
    direction: 'outbound',
    method: 'GET',
    path: '/hello',
    response: hit1.response,
  });

  return {
    sessionId: session.id,
    close: () => session.close(),
  };
}
